apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data: # aqui van los parametros
  port: "8001"
  db_host: mysql8:3306
  database: msvc_usuarios
#  username: root
#  password: root # yo  se que no este
  curso_url: msvc-cursos:8002

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: postgres14:5432
  database: msvc_cursos
#  username: postgres
#  password: root
  curso_url: msvc-usuarios:8001



