apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data: # aqui van los parametros
  lb_auth_issure_uri: http://127.0.0.1:9000
  lb_usuarios_uri: http://127.0.0.1:8001
  port: "8001"
  db_host: mysql8:3306
  database: msvc_usuarios
#  username: root
#  password: root # yo  se que no este
  curso_url: msvc-cursos:8002
  application.yaml: |-
    config:
      texto: Configurando ambiente por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando en ambiente de desarrollo
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Configurando en ambiente de producccion
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: postgres14:5432
  database: msvc_cursos
#  username: postgres
#  password: root
  curso_url: msvc-usuarios:8001



