apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      role: msvc-gateway
  template:
    metadata:
      #hola, soy una etiqueta
      labels:
        role: msvc-gateway
    spec:
      containers:
        - name: msvc-gateway
          image: codigototal/gateway:latest
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
#  tiene que tener el mismo nombre del deployment y del servicio (curso), asi se registrara en el client discovery
  name: msvc-gateway
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090 #puerto del servicio
      targetPort: 8090 #peurto del servicio (deployment)
      #seleccionar los pods, mediante eqiquetas , ten cuiado con la cantidad de etuiquetas
  selector:
    role: msvc-gateway