apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
type: Opaque
data: #la informacion estara codificada - root
  username: cm9vdA==
  password: cm9vdA==

---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data: #la informacion estara codificada - root
  username: cG9zdGdyZXM=
  password: cm9vdA==