spring:
  security:
#  se nos retorna un codigo de aothorizacion por el metodo, de valla... autorizacion xd

    oauth2:
      resourceserver:
        jwt:
          # colocar ruta del servidor de autorizacion
          issuer-uri: http://127.0.0.1:9000
      client:
        registration:
#          podemos registrar diferentes clientes
          msvc-usuarios-client:
            provider: spring
            client-id: usuarios-client
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8001/authorized #recuerda, esto es un load vlancer asi que cambiara yu el otro sera una vaina que generaremos si pasa
            scope: read
            client-name: msvc-usuarios-client
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000 # colocamos la ruta del provedor de seguridad

